### PR TITLE
[issue #98]fix Python error in starting the process

### PR DESCRIPTION
**Pull request by storyofblue**

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
Could you try an alternative fix, and remove lines 115-116 from the file instead?

**Comment by storyofblue** [comment]
OK

**Comment by nyalldawson** [comment]
Can you confirm this new approach also fixes your issue?

**Comment by storyofblue** [comment]
yes it worked

**Comment by storyofblue** [comment]
Why all checks have failed?Are there something wrong?

**Comment by storyofblue** [comment]
There are some error message in a lot of code about checks - `make: *** [pylint] Error 30` and `make: *** [pycodestyle] Error 1`.I think you maight need to think about the Pylint and the PEP8.

**Comment by nyalldawson** [comment]
You can ignore those -- the last update bought in additional linting checks, but the code hasn't yet been updated to pass them all.

**Review by storyofblue — COMMENTED** [review]
Fix Python error in starting the process

**Pull request closed without merging**
